### ISSUE TITLE
convert to tf records : label should be one channel error 

### ISSUE THREAD

**Issue by onizuka94** [DeepSceneSeg/AdapNet-pp#15]
I get this error while trying to convert my trainset into tf records :

    python convert_to_tfrecords1.py --file sorted_train_set.txt --record tf_records_trainset

Exception
Traceback (most recent call last):
File "convert_to_tfrecords1.py", line 54, in convert
assert len(label.shape)==2
AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "convert_to_tfrecords1.py", line 98, in
main()
File "convert_to_tfrecords1.py", line 95, in main
convert(file_list, record_name, mean_flag)
File "convert_to_tfrecords1.py", line 57, in convert
raise( AssertionError( "Label should be one channel!" ) )
AssertionError: Label should be one channel!

Note that images are read in grayscale as I modified line 52 to :
label = cv2.imread(name[1], cv2.IMREAD_GRAYSCALE)
in order for it to work with converting the trainset ,but I don't understand why it's refusing to work for the train set .

**Comment by onizuka94** [comment]
I recreated the sorted_trainset.txt file and it worked , weird behavior .
